/* team proj one
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
*/
package frontend;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.*;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.*;
import javax.swing.border.Border;

/**
 *
 * @author benja
 */
public class HomePageView extends javax.swing.JFrame {
    
    // --- Card identifiers ---
    private static final String CARD_HOME     = "cardHome";
    private static final String CARD_TRANS    = "cardTransaction";
    private static final String CARD_BUDGET   = "cardBudget";
    private static final String CARD_REPORT   = "cardReport";
    private static final String CARD_IMPORT   = "cardImport";
    private static final String CARD_ADD_TRANS   = "cardAddTransaction";
    private static final String CARD_ADD_BUDGET = "cardAddBudget";
    //private static final String CARD_EDIT_TRANS = "cardEditTransaction";
    private static final String CARD_EDIT_BUDGET = "cardEditBudget";
    private static final String CARD_EDIT_CATEGORY = "cardEditCategory";

    // --- Helper method to switch cards ---
    private void showCard(String cardName) {
        java.awt.CardLayout layout = (java.awt.CardLayout) mainPanel.getLayout();
        layout.show(mainPanel, cardName);
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePageView.class.getName());

    /**
     * Creates new form HomePage 
     */
    public HomePageView() {
        initComponents();
        // Register each card with its name
        mainPanel.add(cardHome,        CARD_HOME);
        mainPanel.add(cardTransaction, CARD_TRANS);
        mainPanel.add(cardBudget,      CARD_BUDGET);
        mainPanel.add(cardReport,      CARD_REPORT);
        mainPanel.add(cardImport,      CARD_IMPORT);
        //mainPanel.add(cardEditTransaction,CARD_EDIT_TRANS);
        mainPanel.add(cardAddBudget, CARD_ADD_BUDGET);
        mainPanel.add(cardAddTransaction, CARD_ADD_TRANS);
        //mainPanel.add(cardEditBudget, CARD_EDIT_BUDGET);
        mainPanel.add(cardEditCategory, CARD_EDIT_CATEGORY);

        // Optional: show a default screen when program starts
        showCard(CARD_HOME);
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        projectLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        transactionButton = new javax.swing.JButton();
        budgetButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        cardHome = new javax.swing.JPanel();
        cardTransaction = new javax.swing.JPanel();
        transactionHeader = new javax.swing.JPanel();
        transactionHeaderHeader = new javax.swing.JPanel();
        transactionHeaderButton = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        addTransactionButton = new javax.swing.JButton();
        editTransactionButton = new javax.swing.JButton();
        transactionFilterPanel = new javax.swing.JPanel();
        filterLabel = new javax.swing.JLabel();
        transactionFilterCategorySelect = new javax.swing.JComboBox<>();
        editCategoryButton = new javax.swing.JButton();
        transactionScrollPane = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        cardBudget = new javax.swing.JPanel();
        budgetHeaderPanel = new javax.swing.JPanel();
        budgetHeader = new javax.swing.JLabel();
        addBudgetButton = new javax.swing.JButton();
        editBudgetButton = new javax.swing.JButton();
        budgetScrollPane = new javax.swing.JScrollPane();
        budgetTable = new javax.swing.JTable();
        cardReport = new javax.swing.JPanel();
        reportHeaderPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reportCategorySelected = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        generateReportButton = new javax.swing.JButton();
        reportBodyPanel = new javax.swing.JPanel();
        cardAddBudget = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        addBudgetAmountEntry = new javax.swing.JTextField();
        addBudgetCancelButton = new javax.swing.JButton();
        addBudgetFinishButton = new javax.swing.JButton();
        addBudgetCategorySelect = new javax.swing.JComboBox<>();
        cardImport = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        importFileButton = new javax.swing.JButton();
        cardAddTransaction = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        addTransactionYearSelect = new javax.swing.JComboBox<>();
        addTransactionMonthSelect = new javax.swing.JComboBox<>();
        addTransactionDaySelect = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        addTransactionAmountEntry = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        addTransactionStoreEntry = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        addTransactionCategorySelect = new javax.swing.JComboBox<>();
        cancelAdtTransactionButton = new javax.swing.JButton();
        finishAddTransactionButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        addTransactionItemEntry = new javax.swing.JTextField();
        cardEditCategory = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel12.setText("jLabel12");

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(100, 100, 100));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setBackground(new java.awt.Color(153, 153, 153));
        titlePanel.setPreferredSize(new java.awt.Dimension(100, 50));

        projectLabel.setFont(new java.awt.Font("Old English Text MT", 1, 16)); // NOI18N
        projectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectLabel.setText("PFT");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidebarPanel.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setBackground(new java.awt.Color(100, 100, 100));

        transactionButton.setBackground(new java.awt.Color(100, 100, 100));
        transactionButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transactionButton.setText("Transactions");
        transactionButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        transactionButton.setContentAreaFilled(false);
        transactionButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        transactionButton.setOpaque(true);
        transactionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactionButtonMouseExited(evt);
            }
        });
        transactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionButtonActionPerformed(evt);
            }
        });

        budgetButton.setBackground(new java.awt.Color(100, 100, 100));
        budgetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        budgetButton.setText("Budgets");
        budgetButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        budgetButton.setContentAreaFilled(false);
        budgetButton.setOpaque(true);
        budgetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                budgetButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                budgetButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                budgetButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                budgetButtonMousePressed(evt);
            }
        });
        budgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetButtonActionPerformed(evt);
            }
        });

        reportButton.setBackground(new java.awt.Color(100, 100, 100));
        reportButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reportButton.setText("Reports");
        reportButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportButton.setContentAreaFilled(false);
        reportButton.setOpaque(true);
        reportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportButtonMouseExited(evt);
            }
        });
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(100, 100, 100));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeButton.setContentAreaFilled(false);
        homeButton.setOpaque(true);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        importButton.setBackground(new java.awt.Color(100, 100, 100));
        importButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        importButton.setText("Import");
        importButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        importButton.setContentAreaFilled(false);
        importButton.setOpaque(true);
        importButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                importButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                importButtonMouseExited(evt);
            }
        });
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transactionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(budgetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(importButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(budgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        sidebarPanel.add(buttonPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout cardHomeLayout = new javax.swing.GroupLayout(cardHome);
        cardHome.setLayout(cardHomeLayout);
        cardHomeLayout.setHorizontalGroup(
            cardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        cardHomeLayout.setVerticalGroup(
            cardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        mainPanel.add(cardHome, "card2");

        cardTransaction.setLayout(new java.awt.BorderLayout());

        transactionHeader.setPreferredSize(new java.awt.Dimension(445, 80));
        transactionHeader.setLayout(new java.awt.BorderLayout());

        transactionHeaderHeader.setPreferredSize(new java.awt.Dimension(445, 50));
        transactionHeaderHeader.setLayout(new java.awt.BorderLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setText("Transactions");

        addTransactionButton.setText("Add Transaction [+]");
        addTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTransactionButtonActionPerformed(evt);
            }
        });

        editTransactionButton.setText("Edit Transaction [-]");
        editTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTransactionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transactionHeaderButtonLayout = new javax.swing.GroupLayout(transactionHeaderButton);
        transactionHeaderButton.setLayout(transactionHeaderButtonLayout);
        transactionHeaderButtonLayout.setHorizontalGroup(
            transactionHeaderButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionHeaderButtonLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(addTransactionButton)
                .addGap(18, 18, 18)
                .addComponent(editTransactionButton)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        transactionHeaderButtonLayout.setVerticalGroup(
            transactionHeaderButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionHeaderButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transactionHeaderButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editTransactionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTransactionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        transactionHeaderHeader.add(transactionHeaderButton, java.awt.BorderLayout.CENTER);

        transactionHeader.add(transactionHeaderHeader, java.awt.BorderLayout.PAGE_START);

        transactionFilterPanel.setMinimumSize(new java.awt.Dimension(100, 30));
        transactionFilterPanel.setPreferredSize(new java.awt.Dimension(445, 50));

        filterLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filterLabel.setText("Filter by Category:");

        transactionFilterCategorySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category...", "Dining", "Leisure", "Gifts", "School" }));

        editCategoryButton.setText("Edit Category [+]");
        editCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transactionFilterPanelLayout = new javax.swing.GroupLayout(transactionFilterPanel);
        transactionFilterPanel.setLayout(transactionFilterPanelLayout);
        transactionFilterPanelLayout.setHorizontalGroup(
            transactionFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionFilterPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(filterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionFilterCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(editCategoryButton)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        transactionFilterPanelLayout.setVerticalGroup(
            transactionFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionFilterPanelLayout.createSequentialGroup()
                .addGroup(transactionFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterLabel)
                    .addComponent(transactionFilterCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCategoryButton))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        transactionHeader.add(transactionFilterPanel, java.awt.BorderLayout.CENTER);

        cardTransaction.add(transactionHeader, java.awt.BorderLayout.PAGE_START);

        transactionScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Merchant", "Description", "Amount", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionScrollPane.setViewportView(transactionTable);
        if (transactionTable.getColumnModel().getColumnCount() > 0) {
            transactionTable.getColumnModel().getColumn(0).setResizable(false);
            transactionTable.getColumnModel().getColumn(1).setResizable(false);
            transactionTable.getColumnModel().getColumn(2).setResizable(false);
            transactionTable.getColumnModel().getColumn(3).setResizable(false);
            transactionTable.getColumnModel().getColumn(4).setResizable(false);
        }

        cardTransaction.add(transactionScrollPane, java.awt.BorderLayout.CENTER);

        mainPanel.add(cardTransaction, "card3");

        cardBudget.setLayout(new java.awt.BorderLayout());

        budgetHeaderPanel.setPreferredSize(new java.awt.Dimension(445, 50));

        budgetHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        budgetHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        budgetHeader.setText("Monthly Budget");

        addBudgetButton.setText("Add Budget [+]");
        addBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBudgetButtonActionPerformed(evt);
            }
        });

        editBudgetButton.setText("Edit Budget [-]");
        editBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBudgetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout budgetHeaderPanelLayout = new javax.swing.GroupLayout(budgetHeaderPanel);
        budgetHeaderPanel.setLayout(budgetHeaderPanelLayout);
        budgetHeaderPanelLayout.setHorizontalGroup(
            budgetHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetHeaderPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(budgetHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        budgetHeaderPanelLayout.setVerticalGroup(
            budgetHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, budgetHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(budgetHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(addBudgetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBudgetButton))
                .addContainerGap())
        );

        cardBudget.add(budgetHeaderPanel, java.awt.BorderLayout.PAGE_START);

        budgetScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        budgetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Budget", "Spent", "Remaining"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        budgetScrollPane.setViewportView(budgetTable);
        if (budgetTable.getColumnModel().getColumnCount() > 0) {
            budgetTable.getColumnModel().getColumn(0).setResizable(false);
            budgetTable.getColumnModel().getColumn(1).setResizable(false);
            budgetTable.getColumnModel().getColumn(2).setResizable(false);
            budgetTable.getColumnModel().getColumn(3).setResizable(false);
        }

        cardBudget.add(budgetScrollPane, java.awt.BorderLayout.CENTER);

        mainPanel.add(cardBudget, "card4");

        cardReport.setLayout(new java.awt.BorderLayout());

        reportHeaderPanel.setMinimumSize(new java.awt.Dimension(100, 150));
        reportHeaderPanel.setPreferredSize(new java.awt.Dimension(443, 150));
        reportHeaderPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(443, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reports");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        reportHeaderPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(462, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(462, 38));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(225, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Time Period:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 days", "14 days", "1 month", "2 months", "6 months", "1 year" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Select Category:");

        reportCategorySelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Dining", "Leisure", "Work", "School" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportCategorySelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reportCategorySelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(462, 62));

        generateReportButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        generateReportButton.setText("Generate Report");
        generateReportButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(generateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(generateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        reportHeaderPanel.add(jPanel4, java.awt.BorderLayout.CENTER);

        cardReport.add(reportHeaderPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout reportBodyPanelLayout = new javax.swing.GroupLayout(reportBodyPanel);
        reportBodyPanel.setLayout(reportBodyPanelLayout);
        reportBodyPanelLayout.setHorizontalGroup(
            reportBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        reportBodyPanelLayout.setVerticalGroup(
            reportBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        cardReport.add(reportBodyPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(cardReport, "card6");

        cardAddBudget.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(200, 200, 200));
        jPanel10.setPreferredSize(new java.awt.Dimension(551, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Set Budget Limit");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(176, 176, 176))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(16, 16, 16))
        );

        cardAddBudget.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel13.setPreferredSize(new java.awt.Dimension(551, 250));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Category:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Amount:");

        addBudgetAmountEntry.setText("0.00");
        addBudgetAmountEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBudgetAmountEntryActionPerformed(evt);
            }
        });

        addBudgetCancelButton.setBackground(new java.awt.Color(255, 0, 0));
        addBudgetCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBudgetCancelButton.setText("Cancel");
        addBudgetCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBudgetCancelButtonActionPerformed(evt);
            }
        });

        addBudgetFinishButton.setBackground(new java.awt.Color(0, 255, 0));
        addBudgetFinishButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBudgetFinishButton.setText("Set Limit");
        addBudgetFinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBudgetFinishButtonActionPerformed(evt);
            }
        });

        addBudgetCategorySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBudgetCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addBudgetCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBudgetAmountEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addBudgetFinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(addBudgetAmountEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(addBudgetCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBudgetCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBudgetFinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(414, Short.MAX_VALUE))
        );

        cardAddBudget.add(jPanel13, java.awt.BorderLayout.CENTER);

        mainPanel.add(cardAddBudget, "card9");

        cardImport.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(200, 200, 200));
        jPanel17.setPreferredSize(new java.awt.Dimension(551, 50));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setText("Import File");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel33)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardImport.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        importFileButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        importFileButton.setText("Import");
        importFileButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(importFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(importFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        cardImport.add(jPanel18, java.awt.BorderLayout.CENTER);

        mainPanel.add(cardImport, "card11");

        cardAddTransaction.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(200, 200, 200));
        jPanel11.setPreferredSize(new java.awt.Dimension(551, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("Add Transaction");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(205, 205, 205))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardAddTransaction.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Date:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Year:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Month:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Day:");

        addTransactionYearSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016" }));

        addTransactionMonthSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        addTransactionDaySelect.setMaximumRowCount(32);
        addTransactionDaySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Amount:");

        addTransactionAmountEntry.setText("0.00");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Store Name:");

        addTransactionStoreEntry.setText("Store");
        addTransactionStoreEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTransactionStoreEntryActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Category:");

        addTransactionCategorySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Dining", "Leisure", "Gifts", "Work" }));

        cancelAdtTransactionButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelAdtTransactionButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelAdtTransactionButton.setText("Cancel");
        cancelAdtTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAdtTransactionButtonActionPerformed(evt);
            }
        });

        finishAddTransactionButton.setBackground(new java.awt.Color(0, 255, 0));
        finishAddTransactionButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finishAddTransactionButton.setText("Add");
        finishAddTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishAddTransactionButtonActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Item Name:");

        addTransactionItemEntry.setText("Item");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(addTransactionStoreEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cancelAdtTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(addTransactionItemEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(finishAddTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addTransactionAmountEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addTransactionYearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addTransactionMonthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addTransactionDaySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addTransactionCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(addTransactionYearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(addTransactionMonthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(addTransactionDaySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(addTransactionAmountEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTransactionStoreEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26)
                    .addComponent(addTransactionItemEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(addTransactionCategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAdtTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishAddTransactionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        cardAddTransaction.add(jPanel12, java.awt.BorderLayout.CENTER);

        mainPanel.add(cardAddTransaction, "card8");

        javax.swing.GroupLayout cardEditCategoryLayout = new javax.swing.GroupLayout(cardEditCategory);
        cardEditCategory.setLayout(cardEditCategoryLayout);
        cardEditCategoryLayout.setHorizontalGroup(
            cardEditCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        cardEditCategoryLayout.setVerticalGroup(
            cardEditCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        mainPanel.add(cardEditCategory, "card13");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel16, "card13");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        importFileButton.addActionListener(e-> handleImportFileButtonClick());

        pack();
    }// </editor-fold>

    private void handleImportFileButtonClick() {
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();

        if (!file.getName().endsWith(".csv")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Invalid file type. File must be .csv",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        File selectedFile = file;

        JOptionPane.showMessageDialog(
                this,
                "Selected file:\n" + selectedFile.getName(),
                "File chosen",
                JOptionPane.INFORMATION_MESSAGE
        );
        List<String> data;
        try {
            data = Files.readAllLines(selectedFile.toPath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Could not read file: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (data.size() <= 1) {
            JOptionPane.showMessageDialog(
                    this,
                    "File has no data rows.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        //
        boolean isFormatCorrect = data.stream()
                .skip(1)
                .allMatch(s -> s.matches(
                        "\\d{4}-\\d{2}-\\d{2}\\s*,\\s*[^,]+\\s*,\\s*[^,]+\\s*,-?[0-9]+(\\.[0-9]+)?"
                ));

        if (!isFormatCorrect) {
            JOptionPane.showMessageDialog(
                    this,
                    "CSV format is not correct.\n" +
                            "Expected: date, description, merchant, -amount.decimals",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        List<Transaction> transactions = data.stream()
                .skip(1)
                .map(Transaction::of)
                .collect(Collectors.toList()); //imported csv in list format
    }

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        showCard(CARD_HOME);
    }                                          

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        showCard(CARD_IMPORT);
    }                                            

    private void budgetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        showCard(CARD_BUDGET);
    }                                            

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        showCard(CARD_REPORT);
    }                                            

    private void transactionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        showCard(CARD_TRANS);
    }                                                 

    private void addBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        showCard(CARD_ADD_BUDGET);
    }                                               

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {                                        
        homeButton.setBackground(new java.awt.Color(150,150,150)); // bluish hover
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }                                       

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {                                       
        homeButton.setBackground(new java.awt.Color(100,100,100)); // reset color
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }                                      

    private void transactionButtonMouseEntered(java.awt.event.MouseEvent evt) {                                               
        transactionButton.setBackground(new java.awt.Color(150,150,150)); // bluish hover
        transactionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }                                              

    private void transactionButtonMouseExited(java.awt.event.MouseEvent evt) {                                              
        transactionButton.setBackground(new java.awt.Color(100,100,100)); // reset color
        transactionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }                                             

    private void budgetButtonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        budgetButton.setBackground(new java.awt.Color(150,150,150)); // bluish hover
        budgetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }                                         

    private void budgetButtonMouseExited(java.awt.event.MouseEvent evt) {                                         
        budgetButton.setBackground(new java.awt.Color(100,100,100)); // reset color
        budgetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }                                        

    private void budgetButtonMousePressed(java.awt.event.MouseEvent evt) {                                          
        budgetButton.setBackground(new java.awt.Color(220, 220, 220)); // lighter gray
    }                                         

    private void budgetButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
       
    }                                         

    private void transactionButtonMouseClicked(java.awt.event.MouseEvent evt) {                                               
        transactionButton.setBackground(new java.awt.Color(220, 220, 220)); // lighter gray
    }                                              

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
        homeButton.setBackground(new java.awt.Color(220, 220, 220)); // lighter gray
    }                                       

    private void reportButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        reportButton.setBackground(new java.awt.Color(220, 220, 220)); // lighter gray
    }                                         

    private void reportButtonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        reportButton.setBackground(new java.awt.Color(150,150,150)); // bluish hover
        reportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }                                         

    private void reportButtonMouseExited(java.awt.event.MouseEvent evt) {                                         
        reportButton.setBackground(new java.awt.Color(100,100,100)); // reset color
        reportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }                                        

    private void importButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        importButton.setBackground(new java.awt.Color(220, 220, 220)); // lighter gray
    }                                         

    private void importButtonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        importButton.setBackground(new java.awt.Color(150,150,150)); // bluish hover
        importButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }                                         

    private void importButtonMouseExited(java.awt.event.MouseEvent evt) {                                         
        importButton.setBackground(new java.awt.Color(100,100,100)); // reset color
        importButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }                                        

    private void addBudgetAmountEntryActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void addBudgetCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        showCard(CARD_BUDGET);
    }                                                     

    private void addBudgetFinishButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void editBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        showCard(CARD_EDIT_BUDGET);
    }                                                

    private void addTransactionStoreEntryActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void cancelAdtTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        showCard(CARD_TRANS);
    }                                                          

    private void finishAddTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void editTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        
    }                                                     

    private void editCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        showCard(CARD_EDIT_CATEGORY);
    }                                                  

    private void addTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        showCard(CARD_ADD_TRANS);
    }                                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePageView().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField addBudgetAmountEntry;
    private javax.swing.JButton addBudgetButton;
    private javax.swing.JButton addBudgetCancelButton;
    private javax.swing.JComboBox<String> addBudgetCategorySelect;
    private javax.swing.JButton addBudgetFinishButton;
    private javax.swing.JTextField addTransactionAmountEntry;
    private javax.swing.JButton addTransactionButton;
    private javax.swing.JComboBox<String> addTransactionCategorySelect;
    private javax.swing.JComboBox<String> addTransactionDaySelect;
    private javax.swing.JTextField addTransactionItemEntry;
    private javax.swing.JComboBox<String> addTransactionMonthSelect;
    private javax.swing.JTextField addTransactionStoreEntry;
    private javax.swing.JComboBox<String> addTransactionYearSelect;
    private javax.swing.JButton budgetButton;
    private javax.swing.JLabel budgetHeader;
    private javax.swing.JPanel budgetHeaderPanel;
    private javax.swing.JScrollPane budgetScrollPane;
    private javax.swing.JTable budgetTable;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelAdtTransactionButton;
    private javax.swing.JPanel cardAddBudget;
    private javax.swing.JPanel cardAddTransaction;
    private javax.swing.JPanel cardBudget;
    private javax.swing.JPanel cardEditCategory;
    private javax.swing.JPanel cardHome;
    private javax.swing.JPanel cardImport;
    private javax.swing.JPanel cardReport;
    private javax.swing.JPanel cardTransaction;
    private javax.swing.JButton editBudgetButton;
    private javax.swing.JButton editCategoryButton;
    private javax.swing.JButton editTransactionButton;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JButton finishAddTransactionButton;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton importButton;
    private javax.swing.JButton importFileButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JPanel reportBodyPanel;
    private javax.swing.JButton reportButton;
    private javax.swing.JComboBox<String> reportCategorySelected;
    private javax.swing.JPanel reportHeaderPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton transactionButton;
    private javax.swing.JComboBox<String> transactionFilterCategorySelect;
    private javax.swing.JPanel transactionFilterPanel;
    private javax.swing.JPanel transactionHeader;
    private javax.swing.JPanel transactionHeaderButton;
    private javax.swing.JPanel transactionHeaderHeader;
    private javax.swing.JScrollPane transactionScrollPane;
    private javax.swing.JTable transactionTable;
    // End of variables declaration                   
}

